(import Ontologia.*)
(import examples.jess.*)
(defglobal ?*msg* = nil)
(defglobal ?*ok* = nil)
(deftemplate Information (declare (from-class Information)))
(deftemplate Sample (declare (from-class Sample)))
(deftemplate Gasoline (declare (from-class Gasoline)))
(deftemplate Diesel (declare (from-class Diesel)))
(deftemplate Biodiesel (declare (from-class Biodiesel)))
(deftemplate Alcohol (declare (from-class Alcohol)))
(deftemplate Property (declare (from-class Property)))
